### ISSUE TITLE
Response handling: CG Invoke 201 data parsing

### ISSUE THREAD

**Issue by jesperstarkar** [SuperFlyTV/casparcg-connection#10]

**Comment by jesperstarkar** [comment]
CG INFO as well

**Comment by jesperstarkar** [comment]
CG Invoke is not implemented with any return value in TemplateHost.
CG Info currently only returns in "TemplateHost-mode", not querying a specific template for info. casparcg/server#101 will decide how we do this.

Todo: Parse TemplateHost-info in `CG [channel]-[layer] INFO`

**Comment by baltedewit** [comment]
If I understand correctly, this is fixed as of version 6.0.0 where all received data will be passed to the library consumer.
