### ISSUE TITLE
Access response object

### ISSUE THREAD

**Issue by deedos** [SuperFlyTV/casparcg-connection#103]
Hi, I'm pretty new to this module and I 'm having trouble with the response from commands.
For example, a CINF command with this code:

`const {CasparCG, AMCP} = require("casparcg-connection");
var connection = new CasparCG({
  host: '127.0.0.1',
  autoReconnect: true,
  debug: true, 
  queueMode: 2, // mode: 1  = SALVO mode, default
  onConnectionStatus: (e) => {
   return ("status: ",e);
  }
});
connection.cinf("amb");`

returns me:

`New command added, "CinfCommand". 1 command(s) in command queues.
Can't process commands, socket not connected. 1 commands left in commandsQueue, the first one being "CinfCommand".
Sending command, "CinfCommand" with priority "NORMAL". undefined command(s) in sentCommands, 0 command(s) in command queues.
CINF "amb"
Handling response, "CinfCommand" with token "tp5ag4o"`

CasparCG Server terminal returns me as expected:

`200 CINF OK\r\n"AMB" MOVIE 6445960 20151006174322 268 1/25`

So, Hi do i access the response object ?

Thanks in advance,

**Comment by baltedewit** [comment]
We use promises to access the response data. Something like this: 
```js
connection.cinf('amb').then((resCmd) => console.log(resCmd))
 ```
