### ISSUE TITLE
Connection options host property overrides port property

### ISSUE THREAD

**Issue by baltedewit** [SuperFlyTV/casparcg-connection#110]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
If you create a new CasparCG Instance, and use the connection options object and set the host options, then the port setting will be ignored.
This seems to be related to the check we do for the valid ip address.

```js
const server = new CasparCG({ host: '127.0.0.1', port: 5251 })
console.log(server.port) // 5250
```

* **Other information**
Workaround, set the port in the host option, e.g. `192.168.1.1:5250`

**Comment by olzzon** [comment]
I had the same issue.
Workaround:
Instead put the port as at second argument:
```
const server = new CasparCG({ host: '127.0.0.1'}, 5251)
console.log(server.port) // 5251
```
then things works.

**Comment by olzzon** [comment]
There´s a PR #119 to fix this.

**Comment by olzzon** [comment]
Fixed, so I think we can close this one @baltedewit
