### ISSUE TITLE
Error: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by nytamin** [SuperFlyTV/casparcg-connection#113]
* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
When using the library in a vanilla node project, I get the error `Error: Cannot find module 'tslib'`, due to tslib being required in dist/index.js `const tslib_1 = require("tslib");`

I'm not sure if the correct course of action would be to simply include it in the dependencies, or if we should change tsconfig.json where `"compilerOptions": { "importHelpers": true}`.

Disclaimer: This is a hastily written down issue, I'll probably return in a few days with a PR when I've had time to try it out.

Temporary workaround is simple, just `npm install tslib`

**Comment by TheThing** [comment]
Welp, any updates on this?

It's somewhat annoying to have to manually install tslib just for this project when it shouldn't be needed.

**Comment by fusionstream** [comment]
Can confirm, bug is still present. Solved with a `npm install --save tslib` but I have to agree it's kinda annoying to have to install dependencies yourself.

**Comment by baltedewit** [comment]
This is fixed as of version 6.0.0
