### ISSUE TITLE
mixerContrast/Brightness/Saturation max value >1

### ISSUE THREAD

**Issue by MauriceVeraart** [SuperFlyTV/casparcg-connection#116]
* **I'm submitting a ...**
[ ] feature request

when using the mixerContrast/Brightness/Saturation the max value outputed to CasparCG is 1

for content that needs to be corrected upwards (like underexposed material) or as a artistic effect
a higher max value would be nice

 
* **Summary**

**Comment by baltedewit** [comment]
Good catch! The behaviour is defined here: https://github.com/SuperFlyTV/casparcg-connection/blob/master/src/lib/AMCP.ts#L749 (Note that it's a PositiveNumberValidatorBetween, and should just be a PositiveNumberValidator or have whatever CasparCG has as limit)

Could you change, test and submit a PR perhaps? And if you have the time, I'm sure we must be doing the same in some other places as well (:

**Comment by baltedewit** [comment]
This is fixed as of version 6.0.0 (because it doesn't validate the parameters anymore 🙈)
