### ISSUE TITLE
When using .info command, the datasctructure is not consistent.

### ISSUE THREAD

**Issue by olzzon** [SuperFlyTV/casparcg-connection#121]
When calling .info I get 2 different data structure depending on the media thats loaded in foreground on the channel.

If an image is loaded the foregroundproducer has the filename placed in: "location"
and it´s named e.g. media/xxxxx/xxx/xxx.tiff
If its a videofile the foreground.producer has the filename placed in: "filename"
and it´s named e.g. media//xxx\xxx.mp4

* **Summary**
<img width="415" alt="image" src="https://user-images.githubusercontent.com/29782499/45670863-2e9c1d80-bb24-11e8-8b2f-614d8f3fbdeb.png">

<img width="323" alt="image" src="https://user-images.githubusercontent.com/29782499/45671003-9e120d00-bb24-11e8-8675-52ad2fd44355.png">

**Comment by olzzon** [comment]
I do think that the filename should be stored as it´s done when it´s a videofile. 
e.g. in .ccgconnection.foreground.producer.filename

Workaround for now is to check both places, and both name conventions.

**Comment by olzzon** [comment]
As the INFO command is not used this way in the next versions of CCG, I don´t think anymore focus should be used on it. So I´ll close this one.
Instead I´ll look into CasparCG-state

**Comment by baltedewit** [comment]
> Instead I´ll look into CasparCG-state

We've mostly been using that to generate commands, not track state through receiving commands so YMMV.
But yes, solving this from inside your own application and hoping no one else connects to casparcg is your best bet I guess.
