### ISSUE TITLE
A generic way to call unimplemented AMCP commands

### ISSUE THREAD

**Issue by olzzon** [SuperFlyTV/casparcg-connection#122]
Feature Request:
Is there a way to pass an unimplemented AMCP command?
Otherwise I´d like to see a "DirectAMCP" command, that parses the argument as a string directly. 
This way unimplemented parts of AMCP could be accessible.

**Comment by baltedewit** [comment]
Yes, there is!

```js
const { CasparCG, AMCP } = require('casparcg-connection')

const server = new CasparCG()
const command = new AMCP.CustomCommand('PLAY 1-10')
server.do(command)
```

**Comment by olzzon** [comment]
Thanks.
I´ll close this one again :)

**Comment by z1glr** [comment]
Is there an equivalent command in the current API-version 6.0.0?
