### ISSUE TITLE
THUMBNAIL RETRIEVE FAILED

### ISSUE THREAD

**Issue by Jgaleas7** [SuperFlyTV/casparcg-connection#127]
![cg node error](https://user-images.githubusercontent.com/13549742/50937308-acb86300-1438-11e9-80d8-c862e1575dd2.PNG)

SERVER 2.2 stable
casparcg-connection v 4.6

[error] turn on log level debug for stackrace

**Comment by Julusian** [comment]
Can you provide some more of the log?
In particular the command sent to the server which caused the error, as well as the response.
