### ISSUE TITLE
Possible to controll the Caspar client ?

### ISSUE THREAD

**Issue by Dandrum** [SuperFlyTV/casparcg-connection#139]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ X] question about how to use this project

Is it possible to controll the caspar client from node.js via casparcg-connect ?

I did something with javascript and a socket connection.

Example:
```
    const connection = new WebSocket('ws://127.0.0.1:4250');

    function show(id){
        loadCG(id);
        var myJSON = '{"path" : "/control/'+id+'/play", "args" : [1]}';
        sendCG(myJSON);
    }
    function sendCG(data){
        setTimeout(function () {
            connection.send(data);
        },1000);
    }
```

Then i configure the client OSC and enable remote trigger and set an UID;

Is this also possible from Node.js with this package ?

Why i do this is because i prepare the setup via the client and then someone just start overlays from an web Interface. Like Lower Third and stuff but its possible to use the client and see whats live and so.

Thanks for Help
Greez
Dan

**Comment by baltedewit** [comment]
Hi Dan,
It is not possible to control CasparCG Client with this library. We only support controlling CasparCG Server directly. In order to control CasparCG Client you should use an OSC library.

**Comment by Dandrum** [comment]
Hmm ok thanks for that. I will check out [https://www.npmjs.com/package/osc](npm OSC)
