### ISSUE TITLE
Batch command

### ISSUE THREAD

**Issue by swordh** [SuperFlyTV/casparcg-connection#142]
* **I'm submitting a ...**
[ ] bug report
[ x ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Support for running the batch command BEGIN and COMMIT

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by baltedewit** [comment]
This is implemented as of version 6.0.0

**Comment by anuj998877** [comment]
> This is implemented as of version 6.0.0
@mint-dewit hey may I know where is it implemented?
I tried to search keywords like BEGIN COMMIT but I didn't find any reference to that in the source code.
I appreciate your feedback.

**Comment by mint-dewit** [comment]
You set the `defer` parameter to `true` to any mixer commands you want to defer and then send a mixer commit (i.e. `casparcg.mixerCommit()`)

**Comment by Julusian** [comment]
@mint-dewit thats not the same as the `BEGIN` `COMMIT` syntax that casparcg 2.3+ supports for all commands https://github.com/CasparCG/server/pull/1153
