### ISSUE TITLE
CLS command does not return HTML files

### ISSUE THREAD

**Issue by nchasovnikov** [SuperFlyTV/casparcg-connection#150]
* **I'm submitting a ...**
[+ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

Trying to use media-scanner with nrkno fork of CasparCG (ver. 2.1.10) and latest casparcg-connection.
When subscribing to PouchDB changes it returns all files in the media folder including html files.
But when using CLS command with casparcg-connection it only returns 'video', 'audio' and 'image' file types.

These html files are not templates so are placed in media folder.

Is it supposed to act like this in program versions I'm using?

**Comment by Julusian** [comment]
I am pretty sure that casparcg requires html files to be in the template folder, are you able to play the ones in media?
Scanner detecting the ones in the media folder is the bug (or perhaps an expected limitation). But 2.1 does not use the scanner for media info so will return different results.

**Comment by nchasovnikov** [comment]
I am able to make casparCG play html files providing full path to them and using playHtmlPage command.

**Comment by Julusian** [comment]
If you have to provide the full path to play them then they should not be returned by CLS, as everything returned by that is be playable with just the name it returns.

I am closing this as this library is working as expected, and this should be reopened elsewhere as one of the following:
* media-scanner bug, returning html files when it should not.
* casparcg feature, being able to play html files from the media folder
