### ISSUE TITLE
Wrong parsing for CALL-SEEK response causes disconnect

### ISSUE THREAD

**Issue by Kampflaus** [SuperFlyTV/casparcg-connection#160]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

The CasparCG response for CALL commands with SEEK option is wrongly parsed. In some cases the SEEK framecount will be interpreted as a response status code. The command will then cause a timeout und Caspar will be disconnected after 5 seconds. This is reproducible with some SEEK values, e.g. 1010, 2000, 2010, 4000.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Example Caspar CG 2.3. request and response: 

`REQ v1k84p2 CALL 1-1 SEEK 2000`
`RES v1k84p2 201 CALL OK\r\n2000\r\n`

The newline at the seek value in the response triggers in the following code in **CasparCGSocket.ts** and prevents emitting a response event for wrongly parsed values that match 101, 200, 201, 400:

> private _parseResponseGroups(i: string): void {
> 		global.clearTimeout(this._commandTimeoutTimer)
> 		**i = (i.length > 2 && i.slice(0, 2) === '\r\n') ? i.slice(2) : i**
> 		if (AMCPUtil.CasparCGSocketResponse.**evaluateStatusCode(i)** === 200) {
> 			this._parsedResponse = new AMCPUtil.CasparCGSocketResponse(i)
> 			this._commandTimeoutTimer = global.setTimeout(() => this._onTimeout(), this._commandTimeout)
> 			return
> 		} else if (this._parsedResponse && this._parsedResponse.statusCode === 200) {
> 			if (i !== '\r\n') {
> 				this._parsedResponse.items.push(i)
> 				this._commandTimeoutTimer = global.setTimeout(() => this._onTimeout(), this._commandTimeout)
> 				return
> 			} else {
> 				this.emit(CasparCGSocketResponseEvent.RESPONSE, new CasparCGSocketResponseEvent(this._parsedResponse))
> 				this._parsedResponse = undefined
> 				return
> 			}
> ...

It took us some hours to find the reason for the bug because it was very well hidden. We are suprised that no one else has noticed that disconnect/timeout issue so far. We only found out about it when we saw the disconnects and were not able to send further commands. The reconnect mechanism wasn't working as supposed but that's another issue. Maybe we will open a separate ticket for that.

Best Regards!

**Comment by baltedewit** [comment]
Yeap, that's a nasty one. We don't officially support anything above 2.1 at all but are looking at moving towards 2.3 and will definitely have to rewrite the parsing of responses it seems

**Comment by baltedewit** [comment]
This is fixed as of version 6.0.0
