### ISSUE TITLE
Cinf failing in server 2.3

### ISSUE THREAD

**Issue by Bohoaush** [SuperFlyTV/casparcg-connection#163]
* **I'm submitting a ...**
[ *] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Hi, I've got failed command when I tried cinf with server 2.3 (tested with latest github master, running on Ubuntu 18.04). CasparCG is returning status 201, while casparcg-connection library is expecting 200. After changing the number in response signature, it works as intended. 

May be related to https://github.com/SuperFlyTV/casparcg-connection/issues/41 ?

**Comment by baltedewit** [comment]
This is fixed as of version 6.0.0
