### ISSUE TITLE
Bug: error thrown after force-close of CasparCG

### ISSUE THREAD

**Issue by nytamin** [SuperFlyTV/casparcg-connection#17]
Sometimes, after I've force-closed casparCG I get the following error thrown:
`\casparcg-connection\js\CasparCG.js:445`
`if (!(currentCommand.response instanceof AMCPResponse)) {`
`TypeError: Cannot read property 'response' of undefined`
`    at CasparCG._handleSocketResponse (node_modules\casparcg-connection-bridge\node_modules\casparcg-connection\js\CasparCG.js:445:29)`
`    at CasparCG.<anonymous> (node_modules\casparcg-connection\js\CasparCG.js:120:96)`
`    at CasparCG.emit (events.js:95:17)`
`    at bubble (node_modules\casparcg-connection\node_modules\hap\lib\EventEmitter.js:107:13)`
`    at node_modules\casparcg-connection\node_modules\hap\lib\EventEmitter.js:103:9`
`    at Array.forEach (node_modules\es5-shim\es5-shim.js:435:21)`
`    at bubble (node_modules\casparcg-connection\node_modules\hap\lib\EventEmitter.js:102:24)`
`    at CasparCGSocket.extend.fire (node_modules\casparcg-connection\node_modules\hap\lib\EventEmitter.js:315:5)`
`    at CasparCGSocket._parseResponseGroups (node_modules\casparcg-connection\js\lib\CasparCGSocket.js:268:18)`
`    at node_modules\casparcg-connection\js\lib\CasparCGSocket.js:51:140`
`    at node_modules\casparcg-connection\node_modules\highland\lib\index.js:1725:`

**Comment by jesperstarkar** [comment]
Should be resolved by 6319c29
