### ISSUE TITLE
cgAdd command dosn't work

### ISSUE THREAD

**Issue by alex-Arc** [SuperFlyTV/casparcg-connection#180]
* I'm submitting a **bug report** 

* **Summary**
  - The cgAdd command dosn't work

* **Other information** 
  - Caspar expects a 0 or 1 for the playOnLoad parameter not true or false
  - temporarily fixed on my end by changing the parameters.d.ts file from

```
export interface CgAddParameters extends ChannelLayer, CGLayer {
    template: string;
    playOnLoad: boolean;
    data?: Record<string, any> | string;
}
```
to 
```
export interface CgAddParameters extends ChannelLayer, CGLayer {
    template: string;
    playOnLoad: number;
    data?: Record<string, any> | string;
}
```

**Comment by baltedewit** [comment]
Thank you for opening this issue. This is fixed in version 6.0.2
