### ISSUE TITLE
upgrade from v5 to v6

### ISSUE THREAD

**Issue by fgraux** [SuperFlyTV/casparcg-connection#198]
Hi I'm submitting a question about how to use this project

I have an app using casparcg-connection v5 to send commands to CasparCG.
I want to update to V6, but when I try the basic example of code you provided,
the console return "undefined".
Therefore, when I want to send infoconfig() to retrieve the config,  I don't receive anything, which is a bit annoying.

I tried : 
const { error, request } = CasparCG_Connection.infoConfig()
				if (error) { console.log('Error when sending', error) }
				else { info = await request; console.log(info) }

but it returns  "undefined", when I expect to get paths, channels videomode...

How should I proceed ?
Thanks

**Comment by mint-dewit** [comment]
Your example is not valid javascript (or incomplete) so I can't tell if anything is wrong with it.

**Comment by fgraux** [comment]
Sorry
here is my full script:

`const { CasparCG } = require('casparcg-connection')

const CasparCG_Connection = new CasparCG({
	host: 'localhost',
	port: '5250',
	autoConnect: true,
	onError: function(error){ console.log(error)}
});

async function play() {
	const { error, request } = CasparCG_Connection.infoConfig()
	if (error) {
		console.log('Error when sending', error)
	} else {
		const info = await request
		console.log(info)
	}
}
play()`

**Comment by Julusian** [comment]
That should be `const { error, request } = await CasparCG_Connection.infoConfig()`

We have an unusual double layering of promises. The first promise resolves once the command has been sent, the second one resolves once the command has been executed by CasparCG

**Comment by fgraux** [comment]
thanks but now it returns this error:

Error when sending Error [ERR_SOCKET_CLOSED_BEFORE_CONNECTION]: Socket closed before the connection was established
    at new NodeError (node:internal/errors:399:5)
    at Socket.onClose (node:net:911:10)
    at Object.onceWrapper (node:events:628:26)
    at Socket.emit (node:events:525:35)
    at TCP.<anonymous> (node:net:322:12) {
  code: 'ERR_SOCKET_CLOSED_BEFORE_CONNECTION'
}
I use this with the 2.3.3_LTS CasparCG version

**Comment by fgraux** [comment]
thanks a lot 
I found out 
CasparCG doesnt like when I call it 'localhost' !!!
Prefers 127.0.0.1 or any birdy name

**Comment by Julusian** [comment]
> CasparCG doesnt like when I call it 'localhost' !!!
Prefers 127.0.0.1 or any birdy name

That sounds similar to an issue that scanner/casparcg had a few months ago. In that case it was the scanner binding to only ipv4, and casparcg trying to access it via `localhost` over ipv6.
Your issue was probably the same, but with casparcg binding to only ipv4, and `localhost` resulting in this connection using ipv6
