### ISSUE TITLE
bug on keyer command

### ISSUE THREAD

**Issue by fgraux** [SuperFlyTV/casparcg-connection#202]
Hi there
found a new bug I found while sending keyer command to a Channel / Layer:
CasparCG only receives remove command.

Ex:
Whether I send `const { error, request } = await CasparCG_Connection.mixerKeyer({ channel: 1, layer: 1, value: true, duration: 25, tween: 'EaseInSine'})` or `const { error, request } = await CasparCG_Connection.mixerKeyer({ channel: 1, layer: 1, value: false, duration: 25, tween: 'EaseInSine'}) `
CasparCG returns `MIXER 1-1 KEYER 0\r\n` where it is supposed to return alternatively `MIXER 1-1 KEYER 1\r\n` and  `MIXER 1-1 KEYER 0\r\n`

My best

**Comment by Julusian** [comment]
I think it is expecting `keyer` instead of `value`

**Comment by fgraux** [comment]
exact & thx
sorry
