### ISSUE TITLE
Timeout-errors can't be catched

### ISSUE THREAD

**Issue by z1glr** [SuperFlyTV/casparcg-connection#208]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Since the timeouts of the AMCP-requests are handled through setInterval (see [api.ts, line 122](https://github.com/SuperFlyTV/casparcg-connection/blob/master/src/api.ts#L122), they can't be caught and handled and crash the program instead.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
Maybe replacing setInterval with another method or rejecting the requests somewhere from where they can be catched would be a solution,.

**Comment by nytamin** [comment]
I did a quick test locally and the throwing of timeout errors seems to work as expected, at [line 241](https://github.com/SuperFlyTV/casparcg-connection/blob/master/src/api.ts#L241), the request is rejected properly.

I did however notice an issue in the README file, where an `await` was missing on the initial command, if you don't do the initial await, the uncaught throw might crash the system.

```
const connection = new CasparCG()
	// Note the await on the next line:
	const { error, request } = await connection.play({ channel: 1, layer: 1, clip: 'amb' })
	if (error) {
		console.log('Error when sending', error)
	} else {
		console.log('sent command')
		const response = await request
		console.log('received response of the command', response)
	}
```

**Comment by z1glr** [comment]
Thank you.
Looks like I was going in a circle missing some problems in my code.
Can confirm it works as intended.
