### ISSUE TITLE
Unable to send commands

### ISSUE THREAD

**Issue by baltedewit** [SuperFlyTV/casparcg-connection#4]
Sending any commands using the library gives me the following error:

`throw new Error("Invalid command or commandstring");`

Code is looking as follows:

```javascript
const CasparcgConnection = require('../casparcg-connection/js/CasparCG.js')

var casparServer = new CasparcgConnection.CasparCG({debug: true});
casparServer.play(1, 10);
```

Library is initiated succesfully and a connection to CasparCG is made.

**Comment by jesperstarkar** [comment]
Probably fixed by https://github.com/SuperFlyTV/casparcg-connection/commit/f76bdf917b244c9528d46fc305e002de4b723ceb#diff-2f29066cf1167df06d0e09922359a61c which adds a default ID to all commands. 

Please pull and test latest.

**Comment by jesperstarkar** [comment]
Didn't mean to close...

**Comment by baltedewit** [comment]
That is correct, my fork was out of date.

Issue can be closed.
