### ISSUE TITLE
Implement CALL-command

### ISSUE THREAD

**Issue by busla** [SuperFlyTV/casparcg-connection#50]
I´m trying to send a string from a web client to a CCG server which renders a HTML5 template. Normally I would use `CALL 1-1 UPDATE STRING`. 

How would I implement this using casparcg-connection?

thanks 😄

**Comment by jesperstarkar** [comment]
Sorry, CALL is one of the few not implemented yet. I will have a look at it.

**Comment by busla** [comment]
Thanks for the quick reply 😄 

.. and for sharing.

**Comment by busla** [comment]
This will fix my issue in the meantime:
https://github.com/respectTheCode/node-caspar-cg/blob/master/lib/connection.js#L192

**Comment by busla** [comment]
Just read this issue, I guess I could AMCP customCommand?

https://github.com/SuperFlyTV/casparcg-connection/issues/54#issuecomment-275159402

**Comment by jesperstarkar** [comment]
Sure @busla, I forgot about that one.

**Comment by baltedewit** [comment]
This is fixed as of version 6.0.0
