### ISSUE TITLE
Implement support for HTML producer on LOAD, LOADBG and PLAY

### ISSUE THREAD

**Issue by toontoet** [SuperFlyTV/casparcg-connection#52]
I'm currently trying to us the library for loading and playing HTML based content from external URL's. But is seems not implemented. Am I right?

Using HTML in a PLAY, LOAD or LOADBG command uses the `[html]` helper in front of the clipname. If I add this manually to the clipname it doesn't work. I guess because of the enclosing quotes that are added.

```
201 HELP PRODUCER OK
HTML Producer

Syntax:
  {[html_filename:string]},{[HTML] [url:string]}

Embeds an actual web browser and renders the content in realtime.

HTML content can either be stored locally under the templates folder or fetched
directly via an URL. If a .html file is found with the name html_filename under
the templates folder it will be rendered. If the [HTML] url syntax is used
instead, the URL will be loaded.

Examples:

  >> PLAY 1-10 [HTML] http://www.casparcg.com

  >> PLAY 1-10 folder/html_file
```

This is what CasparCG received:
`Received message from 127.0.0.1: LOADBG 1-1 "[html] http://www.breakingbits.nl"\r\n`

**Comment by jesperstarkar** [comment]
Thank you so much. This is a godd and important request.

**Comment by lklepner** [comment]
I'm trying to do what was described above and I'm getting the error "running without renderer sandbox".  

Is this the correct command syntax?

const {CasparCG} = require("casparcg-connection");
var connection = new CasparCG();
connection.loadHtmlPage(1, 1, 'http://www.google.com')

**Comment by jesperstarkar** [comment]
loadHtmlPage just loads the page in the background. You need a play()-command after this, or just use playHtmlPage() instad, which both loads and plays.

**Comment by lklepner** [comment]
That did it - many thanks!

**Comment by elanvrt** [comment]
This is a very useful command to load an URL without the need to put it in an <iframe> (which is often refused) 
My question is: Is it also possible to "click" on such a loaded web page, so we can interact with it?
