### ISSUE TITLE
autoReconnect doesn't reconnect until next command

### ISSUE THREAD

**Issue by toontoet** [SuperFlyTV/casparcg-connection#66]
I noticed that when autoReconnect is used the connection is only reconnected once a new command is fired. Before that there aren't any attempts. 
Maybe this is on purpose but when a connection to CasparCG is lost it's best to reconnect asap I guess. Else the next command might get delayed. 

I used this script to reproduce. Just after startup or a 'play' message I restart CasparCG. I expect a reconnection attempt within a second cause the default reconnectionTimeout is 1000ms. Reconnection is only done when the next interval is processed. 

```
const {CasparCG} = require("casparcg-connection");

var connection = new CasparCG({
  host: '127.0.0.1',
  autoReconnect: true,
  onConnectionStatus: (e) => {
   console.log("Status: ",e);
  }

});

connection.play(1,1,"amb");
setInterval(()=>{
 console.log(new Date(),"play");
 connection.play(1,1,"amb");
},20000);
```

**Comment by jesperstarkar** [comment]
Thank you for reporting this. I will try and reproduce. Your assumptions are right, it should re-connect within a second.

**Comment by jesperstarkar** [comment]
@toontoet One question though: how did you restart CasparCG?

**Comment by toontoet** [comment]
Different scenario's tested:
- disconnecting network
- `KILL` command in CG
- Closed terminal running CasparCG

**Comment by jesperstarkar** [comment]
2.0.7 or 2.1.0?

**Comment by toontoet** [comment]
2.1.0 on linux

**Comment by jesperstarkar** [comment]
Thanks, I will have a look soon, as this is relevant for ongoing in-house development here at the moment.

**Comment by toontoet** [comment]
It's caused by that if CasparCG closed the 'close' event is fired with hasError false. Then reconnection is not started yet:

https://github.com/SuperFlyTV/casparcg-connection/blob/master/src/lib/CasparCGSocket.ts#L329

**Comment by jesperstarkar** [comment]
This is by design. You should only reconnect if there is unexpected problems. KILL means your's shutting down the server. I don't think we should reconnect after this, or should we? I also think KILL closes the socket to the client gracefully, and this is done differently in 2.0.7 and 2.10. I can look into that.

Disconnecting network and forcing casparcg to shut down should both trigger reconnection.

Perhaps you are right, we could remove the hadError-statement and try to reconnect in any case.

**Comment by toontoet** [comment]
I didn't try the `KILL` anymore. Dit some testing with just closing the CasparCG process (ctrl-c). Maybe the result is the same ... I don't know.

I did notice some other strange reconnection issues though:

If I start and stop CasparCG very fast I get a situation that the lib thinks it's connected while actually commands aren't send anymore and are queued up. The lib then doesn't even check or respond to disconnections anymore. We've experienced this also in our real application (without starting and stoping CasparCG) where somehow our app still was able to send commands, but CasparCG never received any.

```
Tue Feb 14 2017 22:09:15 GMT+0100 (CET) 'play' true <- (CasparCG->connected == true)
New command added, 9 on queue. Added: "PlayCommand"
DEBUG:  New command added, 9 on queue. Added: "PlayCommand"
```

Another thing we've noticed, but weren't able to reproduce was that sometimes after a reconnect we get into a VERSION storm. We notice that the VERSION command is received by CasparCG but then a lot of times. The lib also reports (from the onConnectionChanged callback) a connected and disconnected state in between the VERSION command. The strange thing is that CasparCG seems to be running normally at that moment. But according the CasparCG log the connection to the client is closed just after the command is received. The VERSION commands are then appended tot the queue for every reconnection. But as every command is causing a disconnect it ends up having a lot of them. 
Why the connection drops after every command is unknown. There are no strange network situations, everything on localhost.
As said, the last scenario we haven't reproduced yet, but we have seen it multiple times in the pas 2 weeks running our app 24/7.

**Comment by jesperstarkar** [comment]
This is interesting information, but probably not directly related to the restart problems. 

We're currently writing 24/7 applications ourselves, so this is something we definitively gonna take care of. 

I guess I need to review the timeout-logic, to prevent blocking the command queue if something gets out of sync between request and response. This will also be better once we implement the new REQ method, and the queue can run asynchronously with multiple parallell commands active. The worst thing happening then is a single command gets stuck in limbo, which won't take down a complete TV-station...

Regarding VERSION and other methods issued from the library: I have some new thought about this library, and I want to do a separation where the connection part is _just_ that, a connection library, and all convenience and logical methods are added in a new object above. Basically stripping down CasparCG() today into CasparCGConnection(), and creating a new CasparCG() giving all sorts of cool features. This way, you can have FULL control over how the connection behaves, and my design choices won't affect you as much. This will be a breaking change, I'm thinking about building it under the "future" branch and merge this into master as V1. In this "future" branch I will also make sure that each command-object has properties matching the parameter signature.

**Comment by jesperstarkar** [comment]
> Perhaps you are right, we could remove the hadError-statement and try to reconnect in any case.

Yep i would really like this actually, having endless reconnection until the connections is told to disconnect() by a command.
