### ISSUE TITLE
Mixer easings doesn't work (a matter of casing)

### ISSUE THREAD

**Issue by nytamin** [SuperFlyTV/casparcg-connection#67]
When I send a Mixer command with a transition, for example {transitionEasing: 'INOUTCUBIC' }
the command sent to Caspar will have the easing INOUTCUBIC, but apparently it should be 'InOutCubic' in order to work.
This applies to both 2.07 & 2.1.
This bug only applies to Mixer transitions (uppercase easings work in PlayCommands).

**Comment by nytamin** [comment]
On second thought, I'm unable to reproduce.. I'll open this again if I encounter this situation again.

**Comment by jesperstarkar** [comment]
AMCP is not case sensitive, so it shouldn't matter.
