### ISSUE TITLE
loadHtmlPage: Error running without renderer sandbox

### ISSUE THREAD

**Issue by lklepner** [SuperFlyTV/casparcg-connection#72]
Hi,

First off - I'm very excited to have found this module and be testing it out for potential use in my application! 

Using telnet I am able to connect to my server instance and load google.com with the following command -
PLAY 1-1 [HTML] "http://www.google.com" \r\n

I'm trying to reproduce the equivalent via casparcg-connection:

const {CasparCG} = require("casparcg-connection");
var connection = new CasparCG();
connection.loadHtmlPage(1, 1, 'http://www.google.com')

In the server log I see the following 
![image](https://cloud.githubusercontent.com/assets/110027/24425327/c91c9e4e-13d1-11e7-8e93-4fb16d435b55.png)

Am I using the wrong command/syntax? 

Thanks!!

Lou

**Comment by jesperstarkar** [comment]
Hi Iklepner.

I answered your question in your original post here: https://github.com/SuperFlyTV/casparcg-connection/issues/52#issuecomment-289888844

I see that we're currently missing "quotes" around the URL in the produced command. I have added this to the Develop branch, and will merge this in the next version bump.

**Comment by lklepner** [comment]
My apologies for the double tap - and thanks for the guidance in the other thread!

**Comment by jesperstarkar** [comment]
No worries. Thank you for taking the time of posting, with log excerpt and all! Much appreciated, and it inspires further development.
