### ISSUE TITLE
serverVersion callback/promise

### ISSUE THREAD

**Issue by realies** [SuperFlyTV/casparcg-connection#73]
I'm getting different results with this code:

```
const cg = new CasparCG({
 onConnected: () => {
  console.log(cg.serverVersion);
  setTimeout(() => console.log(cg.serverVersion), 100);
 });
```

Enabling debug and looking at the code makes me think there's no way of knowing when cg.serverVersion has been populated by VersionCommand. Is this not implemented or I'm missing to listen for something? Testing against CasparCG 2.1.0.3413 02ebf80 Beta 1.

> New command added, 1 on queue. Added: "VersionCommand"
> Sending command, 1 commands sent, 0 commands on queue. Sending: "VersionCommand"
> VERSION SERVER
> 2000
> Handling response, 0 commands sent. Handling: "VersionCommand"
> 2110

**Comment by jesperstarkar** [comment]
Hmm, i thought `serverVersion` was a Promise. But it seems it's not.

Let me have a look at it. And, I want to split the library in two: one part being solely a connection library with the protocol implemented, and this kind of convenience (version, config etc) being a layer on top of it. This will be built in the "future" branch.

**Comment by realies** [comment]
@jesperstarkar, let me know if you could use any help to progress the library.

**Comment by jesperstarkar** [comment]
Sure! Any help is welcome. How do you want to participate? How should we get startedt together?

**Comment by realies** [comment]
I'm currently learning server-side javascript and getting into typescript would be great. I'm thinking that if you could outline a high-level overview of what both libraries should do we could start from somewhere. I'm sure there would be more people that would be interested in contributing. You can also find me on #casparcg at Freenode.

**Comment by jesperstarkar** [comment]
@realies I have started this thread to help us collaborate and discuss: https://github.com/SuperFlyTV/casparcg-connection/issues/74

**Comment by jesperstarkar** [comment]
Oooh, this is a bit trickier than I expected. But I have a plan, and will do it tomorrow, as I need just this feature now.

**Comment by jesperstarkar** [comment]
Wow, it was easier than i thought! It helped sleeping on it.

I'm gonna push this as a "next" master, being the candidate for v3.0.0
