### ISSUE TITLE
do not use npm es6-promise

### ISSUE THREAD

**Issue by super-ienien** [SuperFlyTV/casparcg-connection#75]
Hi,

I'm back on my project using your super library. I am currently facing poblem. You are using es6-promise to polyfill the global promise object. A library should'nt modify a global object. In my case it's not a good thing because i am using bluebird globally by replacing the global Promise object by Bluebird. I know this is not a very good practice but it's very convenient and I am the end user of my project so I can do what i wan't in the global space :)

I saw that you are working on a new version of casparcg-connection. Could you keep this in mind for the Future ?

**Comment by jesperstarkar** [comment]
Hmm, what other kind of promise solution are you suggesting?

**Comment by super-ienien** [comment]
What are your requirements for Promises ? Is es6-promise package here for supporting promise in any kind of web browser ?

**Comment by super-ienien** [comment]
If you don't need enhanced promise like (rxjs or bluebird) you should use JavaScript's built in promise. Es6-promise is just a pollyfill for old browsers. But your library is made to run on nodejs which already support promises.

**Comment by jesperstarkar** [comment]
Please give 2.0.3 a spin super-ienien. A lot of stuff have changed under the hood, so please test it before putting into production. Hope I haven't broken anything...
