### ISSUE TITLE
autoReconnectAttempts bugs

### ISSUE THREAD

**Issue by jesperstarkar** [SuperFlyTV/casparcg-connection#84]
- Not defined in interface
- Wrong implementation between public and private properties
- Does NOT reset in case of connection, reconnection or disconnection actions
- Should fire an event when the socket "gives up" due to max attempts reached.

**Comment by baltedewit** [comment]
autoReconnectAttempts is no longer implemented as of 6.0.0, please reopen as a feature request if this is required.
