### ISSUE TITLE
AMCP.CustomCommand strips brackets from commands

### ISSUE THREAD

**Issue by hreinnbeck** [SuperFlyTV/casparcg-connection#88]
Using:
```caspar.do( new AMCP.CustomCommand( "PLAY 1-1 [HTML] http://google.com" ) );```
Results in the command being sent stripped of brackets:
```PLAY 1-1 HTML http://google.com```

I traced it to line 50 of ParamValidators.js.  Needed a quick fix so simply commented it out.

NOTE: Casparcg-connection should never strip characters that are implemented in AMCP commands.

**Comment by jesperstarkar** [comment]
Of course, it should not strip anything. This is just a bad regex that needs to be taught some manners.

Thank you Hreinn.

**Comment by hreinnbeck** [comment]
After sleeping on it we should perhaps look at this as two different issues.

Validated commands shouldn't strip brackets or other characters allowed/required in commands.

With CustomCommand being such a low level command - it shouldn't do *any* validation as the user is probably using the CustomCommand for a reason. This might be important for future AMCP changes which might not be supported in casparcg-connection.

**Comment by jesperstarkar** [comment]
Resolved in v3.0.0 (with v3.0.1 being the current stable release).
