### ISSUE TITLE
Mixer transition value not sent

### ISSUE THREAD

**Issue by JonFranklin301** [SuperFlyTV/casparcg-connection#89]
Sending a mixer command which contains a transition values results in the value(s) not being sent to the server:

mixerFill does not send the transitionEasing value (tried with different variations of the value):
`connection.mixerFill(1, 1, 0, 0, 0.5, 0.5, 25, 'EASEINOUTSINE', true)`
`connection.mixerFill(1, 1, 0, 0, 0.5, 0.5, 25, 'INOUTSINE', true)`
`connection.mixerFill(1, 1, 0, 0, 0.5, 0.5, 25, 'IN_OUT_SINE', true)`
all result in the following being sent to the server:
`MIXER 1-1 FILL 0 0 0.5 0.5 25 DEFER`

mixerCrop does not send both the transitionDuration and transitionEasing value (or defer):
` connection.mixerCrop(1, 1, 0.25, 0.25, 0.75, 0.75, 25, 'EASEINOUTSINE', true)`
results in the following being sent to the server:
`MIXER 1-1 CROP 0.25 0.25 0.75 0.75`

mixerOpacity does not send the transitionEasing value:
`connection.mixerOpacity(1, 1, 0.5, 25, 'EASEINOUTSINE', true)`
results in the following being sent to the server:
`MIXER 1-1 OPACITY 0.5 25 DEFER`

**Comment by jesperstarkar** [comment]
Thank you so much. Copy/paste typos.

Will be pushed to next and tagged as v3.0.1 soon

**Comment by jesperstarkar** [comment]
No, actually, it will be released as V3.0.1 right away.
