### ISSUE TITLE
ADD IMAGE command missing

### ISSUE THREAD

**Issue by MauriceVeraart** [SuperFlyTV/casparcg-connection#94]
ADD 1 IMAGE filename
http://casparcg.com/wiki/CasparCG_2.0_AMCP_Protocol#ADD

**Comment by jesperstarkar** [comment]
Wow, thanks!

**Comment by MauriceVeraart** [comment]
COOL thanks!!

I see you have added all the other ADD commands too

this is really helping me in a upcoming project

**Comment by Besedin86** [comment]
@MauriceVeraart Not all, but I'm working on this

**Comment by Besedin86** [comment]
@jesperstarkar Who can accept pull request ?

**Comment by MauriceVeraart** [comment]
hmm no clue

**Comment by jesperstarkar** [comment]
Hi! I will merge it quite soon. We're in a development phase were more much needed maintenance will be done, so a few things will happen quite soon.

**Comment by baltedewit** [comment]
Fixed in ca772e68c2ae8bdbb074d0b9557ceed24cf8e742 and released as of version 3.1.0

**Comment by MauriceVeraart** [comment]
Ok it does the job for me thank you guys !!
